name: TapRent
version: 1.1
main: TapRent\Main
author: Artide
description: "Players can now rent homes!"
api: 1.10.0
depend: EconomyAPI

commands:
  home:
   description: "Teleport to rented home!"
   permission: taprent.command.home

permissions:
  taprent.command.rent:
   default: true
